### ISSUE TITLE
Guide for Bottles flatpak?

### ISSUE THREAD

**Issue by ghtesting2020** [AsherGlick/Burrito#117]
Cool project! Have been missing TacO since i left windows. Can someone create a guide on how to do this for Bottles flatpak instead of Lutris? Not having luck by myself.

https://burrito.orthogonalprojects.com/

This is Bottles:
https://flathub.org/apps/details/com.usebottles.bottles
https://github.com/bottlesdevs/Bottles

**Comment by AsherGlick** [comment]
If someone writes guide for this I am happy to add it to the available resources for folks to use as a community guide. I have never used bottles myself but you probably have a few of options. The first two are pretty similar and might not work if you are having trouble with the current documentation. The third one requires a bit of technical skill but will almost certainly work.

Using `burrito_link.exe`
-----------------------
Write a simple shell script to launch burrito_link.exe with the same wine binary and env as being used to launch gw2
If you dont know what env vars you have you might be able to find them by using `strings -a /proc/<pid>/environ` where `pid` is the process id of your running guild wars 2.


Using `burrito_link.exe` auto launch
--------------------
If you know what wine binary you are using you can use that path for the wine path in the config settings.
If you know what environment variables to use you can set them as well in the config settings for autolaunch burrito link
If you dont know what env vars you have you might be able to find them by using `strings -a /proc/<pid>/environ` where `pid` is the process id of your running guild wars 2.


Using burito link as a  `d3d11.dll` library
-------------------------------------
You will have to compile this yourself right now because it still has some bugs when exiting the game, but it will be the simpler solution overall. Once compiled you just drop it into your guild wars 2 folder as if it was any other plugin. No need to set a wine path or env args because it will be launched automatically by the gw2 process, guaranteeing that it has access to the same wine environment as your game.
Check out the [burrito_link_updates](https://github.com/AsherGlick/Burrito/tree/burrito_link_updates) branch and #92 for some more details. If anyone is reading this in the future and the link to that branch does not work it is because it has been merged into master.

**Comment by ghtesting2020** [comment]
Thank you for quick response @AsherGlick! Ideally i could use option 3 but i do not know how to compile an exe. I guess i will wait for it to be merged and released with a new update :)

**Comment by AsherGlick** [comment]
The CMake file should take care of everything as long as you have all the dependencies installed. I can't remember all the dependencies off the top of my head but I am sure it can be figured out.

**Comment by AsherGlick** [comment]
This topic seems to be popular enough that I figure I might as well share a precompiled d3d11.dll file and some light instructions on how to use it. https://burrito.orthogonalprojects.com/#burrito_link_dll once more of the rough edges are ironed out this will be the recommended method of running Burrito Link due to its ease of setup. I am going to close this issue but feel free to re-open it if there is something specific to bottles that does not work with this solution. If there is a generic issue with the d3d11.dll open a new issue so it can be tracked separately from bottles.

**Comment by AsherGlick** [comment]
If you are using the d3d11.dll file you do not need to run burrito_link.exe and you do not have to have it configured to launch inside Burrito itself.  The Burrito window is invisible except for a tiny burrito icon in the top left of the screen, once you click it it will give a red border around the entire area. Sometimes this can be hidden by the operating system bar at the top of the screen.

burrito_link.exe wont be managed by GW2, if you are using the auto launch functionality from burrito then burrito will try to kill it when burrito closes, however burrito_link.exe also has the option for a termination timeout in case burrito cannot kill it. This means that even if burrito_link.exe is orphaned by burrito it will still eventually exit.

If you are using the d3d11.dll file then that library will be unloaded automatically when GW2 exits, but it should not be showing up a burrito_link.exe in your processes list.

**Comment by NiPfi** [comment]
I just added a shortcut to burrito_link to the programs list in the same bottle and ran it after GW2. It seems like that did the trick, because if it's in the same bottle, it'll run using the same WINE environment, as far as I understand.
