### ISSUE TITLE
Steam Documentation

### ISSUE THREAD

**Issue by ThatGuy435** [AsherGlick/Burrito#118]
I'm not sure how exactly would be best to add to the documentation, but burrito_link.exe can be run in the Steam proton container via protontricks

`protontricks -c "wine /path/to/burrito_link.exe" 1284210`

This requires protontricks, but that should be available in most repos - certainly in Linux Mint (where I have used protontricks for other games) and Fedora 37 (which is where I'm testing this currently).

After that, burrito.x86_64 can be run normally and seems to pick everything up from there.

**Comment by HanPrower** [comment]
You can alternatively use [SteamTinkerLaunch](https://github.com/sonic2kk/steamtinkerlaunch) and fork `burrito_link.exe` when the game exe launches:
![image](https://user-images.githubusercontent.com/1781312/212347665-b5efa7b7-d10b-4015-924d-1ee1f79ec9e6.png)

**Comment by SchoolGuy** [comment]
openSUSE doesn't have protontricks in the repos atm officially. I would highly appreciate if the setup process is simpler in the future.

**Comment by AsherGlick** [comment]
This topic seems to be popular enough that I figure I might as well share a precompiled d3d11.dll file and some light instructions on how to use it. https://burrito.orthogonalprojects.com/#burrito_link_dll once more of the rough edges are ironed out this will be the recommended method of running Burrito Link due to its ease of setup. I am going to close this issue but feel free to reopen it if there is something specific to running burrito link with steam. If there is a generic issue with d3d11.dll open a new issue so it can be tracked separately.
