### ISSUE TITLE
Please explain how to convert taco xml to json to a normal person!

### ISSUE THREAD

**Issue by Sinaaaa** [AsherGlick/Burrito#155]
Hello!

With some difficulty I managed to set up Burrito to work with the marker pack downloaded from the Burrito website. However some stuff I need is missing, for example guild missions. I plan to jump on SOTO packs as soon as they are released as well. So how do I use the provided XML parsers? (either from here or the jlloh forked repo)

If I want to use the "taco_to_burrito.py" how is the parameter syntax for this, how do I give it file locations etc, how do I give it input?  (I tried and failed with some basic stuff)

Then there is the other "very simple util", where the readme says 

"Usage
`let json_str = taco_to_json_str("folder_name", "test.xml");`
"
Needless to say I have no idea how to set it up to the point where that command would do work.

--

I'm stuck, please at least give me a few hints. (I did clone both repos & tried some stuff, but ..) 

Anyway thanks for the great work that you do, Burrito is already quite great.

**Comment by AsherGlick** [comment]
**To a normal person**
1) Use some else's converted marker packs
2) Try to load the xml marker pack with Open Markers File. This will only work if the XML is perfectly formatted, which most marker packs are not.
3) Wait for #64 to be completed which will just let you load all taco marker packs no problem

**To someone who knows how to run python**
The instructions for how to use `taco_to_burrito.py` get printed out when you call it with no arguments. I have copied it here for you
```
USAGE: taco_to_burrito.py SRC_DIR DEST_DIR
```
eg:
``` bash
python3 taco_to_burrito.py some_xml_marketpack_folder/ my_new_json_markerpack_folder/
```

This will also require the XML to be syntactically correct however, which many marker packs are not. This is because taco's xml parser allows for a lot of errors in the xml so marker packs end up not knowing they have errors. This process will probably give you more insight to what the xml errors are however, and they can then be manually fixed.

**Comment by Sinaaaa** [comment]
Thanks a lot for the answer! 

I feel a bit stupid right now, but admittedly I have never python code before, code that has not been installed with pip anyway.. I made the py file executable and upon running it things seems to have happened and so I thought i'm doing it right, since I had all the python dependencies installed ;;_+. In retrospect I really should have known that wouldn't work..

I managed to successfully feed "taco_to_burrito.py" the guild mission xml file. You weren't kidding about the errors..
