### ISSUE TITLE
Burrito cannot parse .taco pack

### ISSUE THREAD

**Issue by ngraham20** [AsherGlick/Burrito#302]
I don't know if this is a recent issue, but the .taco pack I got from [fast farming](https://fast.farming-community.eu/farming/guides/fast-taco-marker) does not convert when using the conversion script, and it won't open if I just try to open the taco file directly. It seems that the conversion script assumes the file to be `.xml`, but it's a binary file instead.

**Comment by AsherGlick** [comment]
Taco files dont 100% work yet. There is a rust-based xml parser that we are working on replacing with a much more robust solution.

However you might have some luck if you extract the `.taco` file first and try to load the `.xml` files inside. A `.taco` file is just a `.zip` file that has been renamed. Otherwise you can follow https://github.com/AsherGlick/Burrito/issues/64 for the status of the new xml parser

**Comment by ngraham20** [comment]
Sounds good, thanks for the tip!
