### ISSUE TITLE
VirusTotal flagged Alpha 1.4 release file as malicious

### ISSUE THREAD

**Issue by leonyu** [AsherGlick/Burrito#368]
VirusTotal flagged Alpha 1.4 release file as malicious

https://www.virustotal.com/gui/file/f26cac3d9774ab3cd7c721c8856af6c2396fcaadcd0553ca6495c89c213f2e44

Specifically `burrito_link.exe`

https://www.virustotal.com/gui/file/2e4e1a796b2a32b22b91af2b1b555d0ade77325c42b85e78ec96179ec69d2b5f

Though arcdps gets similar treatment.

**Comment by Technetium1** [comment]
Only 2 generic detections from unpopular 'ai cybersecurity' products. Normal false positive.

**Comment by AsherGlick** [comment]
I am not sure what to do about this, virustotal gives no information about what the error actually is. Burrito link could easily show up as a false positive because it is basically an injectable or standalone library that reads and exfiltrates memory over a udp socket. However that socket is always connecting to localhost and that memory is a named shared memory block so any tool that cannot parse that constraint is likely to have a false positive. Additionally the injectable and standalone executable versions of burrito link are built from nearly the same source code, just with different entrypoints. Yet a check that flags one of those files as problematic does not flag the other one.

https://www.virustotal.com/gui/file/2e4e1a796b2a32b22b91af2b1b555d0ade77325c42b85e78ec96179ec69d2b5f/detection
https://www.virustotal.com/gui/file/163c18edd6d04e52cd5985edadc14871809bfccdcf49881644de99e2a9892fe0/detection

I do appreciate being made aware of this, but unless this can be linked to a real user facing problem I'm going to go ahead and close this issue because there is nothing for us to fix.

**Comment by leonyu** [comment]
Yea, I believe it is false positive as well due to how ArcDPS and this addon works. Just brought up in case you wish to fiddle with implementation to engineer around the problems. 

Feel free to close.
